modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License version 3"

[[mods]]
modId="arsmeteorites"
version="1.1.6"
displayName="Ars Meteorites"
description="An addon for Ars Nouveau adding meteorite magic"
displayURL = "https://github.com/wanggugu197/Ars-Meteorites"
authors="maple197"
credits=""

[[dependencies.arsmeteorites]]
modId="ars_nouveau"
versionRange="[4.12.6,)"
mandatory=true